import time
import os
import random
import argparse
from typing import List
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from web_utils import setup_chrome_driver

# Configuration
# Set this to your Brave User Data path if you want to stay logged in.
# Usually: r"C:\Users\<Username>\AppData\Local\BraveSoftware\Brave-Browser\User Data"
# WARNING: Brave must be COMPLETELY CLOSED for this to work.
USER_DATA_DIR = None  # Set this to your browser's user data path to stay logged in
PROFILE_DIRECTORY = "Default"
SPOTIFY_SEARCH_URL = "https://open.spotify.com/search/"


def get_songs_from_file(filename: str) -> List[str]:
    """
    Parses the text file generated by the scraper.
    
    Args:
        filename: Path to the file containing songs.
        
    Returns:
        A list of song search queries.
    """
    songs = []
    if not os.path.exists(filename):
        print(f"Error: {filename} not found.")
        return songs
        
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            clean_line = line.strip()
            if not clean_line:
                continue
                
            # Use the full text after the index part "1. "
            try:
                if '. ' in clean_line[:10]:
                    search_query = clean_line.split('. ', 1)[1].strip()
                else:
                    search_query = clean_line
                songs.append(search_query)
            except Exception:
                songs.append(clean_line)
    return songs


def add_to_spotify_liked(filename: str):
    """
    Search for songs on Spotify and add them to 'Liked Songs'.
    
    Args:
        filename: Path to the text file containing songs.
    """
    songs = get_songs_from_file(filename)
    if not songs:
        print(f"No songs to process in {filename}.")
        return

    print(f"Loaded {len(songs)} songs from {filename}")
    
    if USER_DATA_DIR and not os.path.exists(USER_DATA_DIR):
        print(f"WARNING: User data directory not found at {USER_DATA_DIR}")
        # We continue as user might have intentionally left it None for manual login

    driver = setup_chrome_driver(
        user_data_dir=USER_DATA_DIR,
        profile_directory=PROFILE_DIRECTORY,
        stealth_mode=True,
        start_maximized=True
    )

    wait = WebDriverWait(driver, 15)
    actions = ActionChains(driver)

    try:
        print("Navigating to Spotify Search...")
        driver.get("https://open.spotify.com/")
        
        # Check if login is needed
        print("Checking login status...")
        time.sleep(5)  # Allow time for profile to load
        
        for i, query in enumerate(songs):
            print(f"[{i + 1}/{len(songs)}] Searching for: {query}")
            
            # Navigate to search results directly
            driver.get(f"{SPOTIFY_SEARCH_URL}{query}")
            
            try:
                # Wait for search results to appear
                wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'div[data-testid="tracklist-row"]')))
                
                # Get the first track row
                first_track = driver.find_element(By.CSS_SELECTOR, 'div[data-testid="tracklist-row"]')
                
                # Check if already liked
                try:
                    like_button = first_track.find_element(By.CSS_SELECTOR, 'button[data-testid="add-button"]')
                    aria_label = like_button.get_attribute("aria-label")
                    
                    if any(msg in aria_label for msg in ["Remove from Your Library", "Already in Your Library"]):
                        print(" -> [SKIP] Already liked.")
                        continue
                except Exception:
                    pass

                # Right click the first track
                actions.context_click(first_track).perform()
                time.sleep(1.5)

                # Check if the song is already liked via context menu
                try:
                    remove_selectors = [
                        "//span[contains(text(), 'Remove from your Liked Songs')]",
                        "//span[contains(text(), 'Remove from Liked Songs')]",
                        "//span[contains(text(), 'Remove from Your Library')]"
                    ]
                    
                    is_already_liked = False
                    for selector in remove_selectors:
                        if driver.find_elements(By.XPATH, selector):
                            print(" -> [SKIP] Song already in liked songs (detected in menu).")
                            is_already_liked = True
                            break
                    
                    if is_already_liked:
                        actions.move_by_offset(0, 0).click().perform()
                        continue
                except Exception:
                    pass

                # If not already liked, look for "Save to your Liked Songs"
                try:
                    add_selectors = [
                        "//span[contains(text(), 'Save to your Liked Songs')]",
                        "//span[contains(text(), 'Add to Liked Songs')]",
                        "//button[contains(., 'Save to your Liked Songs')]",
                        "//span[contains(text(), 'Save to Your Library')]"
                    ]
                    
                    added = False
                    for selector in add_selectors:
                        try:
                            menu_item = driver.find_element(By.XPATH, selector)
                            menu_item.click()
                            print(" -> [SUCCESS] Added to Liked Songs.")
                            added = True
                            break
                        except Exception:
                            continue
                    
                    if not added:
                        print(" -> [FAIL] Could not find 'Add to Liked' in menu.")
                        actions.move_by_offset(0, 0).click().perform()
                
                except Exception as menu_err:
                    print(f" -> [ERROR] Menu interaction failed: {menu_err}")

            except Exception:
                print(f" -> [NOT FOUND] No results or structure changed for: {query}")
            
            # Random delay to mimic human behavior
            time.sleep(random.uniform(2, 4))

    except Exception as e:
        print(f"Critical error: {e}")
    finally:
        print("Tasks complete. Closing browser in 10 seconds...")
        time.sleep(10)
        driver.quit()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Move songs to Spotify Liked Songs.")
    parser.add_argument("filename", help="Path to the text file containing songs")
    args = parser.parse_args()
    
    add_to_spotify_liked(args.filename)
